// <auto-generated />
using System;
using CommandsTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CommandsTest.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17");

            modelBuilder.Entity("CommandsTest.Models.Commands", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Commands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("718c1632-7a63-4bae-95dc-fdb3bc7f4328"),
                            Description = "Description 1",
                            Key = "Key 1"
                        },
                        new
                        {
                            Id = new Guid("83172ede-5931-4881-bd0f-bf1790d4ba65"),
                            Description = "Description 2",
                            Key = "Key 2"
                        },
                        new
                        {
                            Id = new Guid("ba5e6122-709b-43e6-8082-244d3183a3e2"),
                            Description = "Description 3",
                            Key = "Key 3"
                        },
                        new
                        {
                            Id = new Guid("a62381fa-fb5d-4b7a-8b79-252879dfe8ba"),
                            Description = "Description 4",
                            Key = "Key 4"
                        },
                        new
                        {
                            Id = new Guid("d94de2b9-c058-4599-9e73-5e4bb94283df"),
                            Description = "Description 5",
                            Key = "Key 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
